version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: libero
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - libero-net
    deploy:
      placement:
        constraints:
          - node.role == worker

  backend:
    image: projetlibero/libero-backend:latest
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://admin:admin@postgres:5432/libero
    depends_on:
      - postgres
    networks:
      - libero-net
    ports:
      - "3000:3000"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  frontend:
    image: projetlibero/libero-frontend:latest
    depends_on:
      - backend
    networks:
      - libero-net
      
    # ports:
    #   - "80:5173"
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure

volumes:
  postgres_data:

networks:
  libero-net:
    external: true
