//voir si possible de faire encore plus generique

export const ERROR_CODES = {
  // QuoteTemplate
  TEMPLATE_NAME_EXISTS: 'TEMPLATE_NAME_EXISTS',
  TEMPLATE_NOT_FOUND: 'TEMPLATE_NOT_FOUND',
  TEMPLATE_VARIABLE_NAME_CONFLICT: 'TEMPLATE_VARIABLE_NAME_CONFLICT',
  TEMPLATE_VARIABLE_NAME_RESERVED: 'TEMPLATE_VARIABLE_NAME_RESERVED',
  TEMPLATE_VARIABLE_REQUIRED_MISSING: 'TEMPLATE_VARIABLE_REQUIRED_MISSING',

  // Quote
  QUOTE_NUMBER_DUPLICATE: 'QUOTE_NUMBER_DUPLICATE',
  QUOTE_NOT_FOUND: 'QUOTE_NOT_FOUND',

  // Client
  CLIENT_EMAIL_DUPLICATE: 'CLIENT_EMAIL_DUPLICATE',
  CLIENT_NOT_FOUND: 'CLIENT_NOT_FOUND',

  // Auth / User
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_EMAIL_EXISTS: 'USER_EMAIL_EXISTS',
  UNAUTHORIZED: 'UNAUTHORIZED',

  // Generic
  BAD_REQUEST: 'BAD_REQUEST',
  FORBIDDEN: 'FORBIDDEN',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;
