name: Deploy Libero to Swarm

on:
  push:
    branches:
      - clusterisation-v2

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      REGISTRY: docker.io
      IMAGE_BACKEND: docker.io/projetlibero/libero-backend:latest
      IMAGE_FRONTEND: docker.io/projetlibero/libero-frontend:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ env.IMAGE_BACKEND }}

      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ env.IMAGE_FRONTEND }}

      - name: Upload docker-stack.yml to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.OVH_HOST }}
          username: ${{ secrets.OVH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker-stack.yml"
          target: "/home/ubuntu/libero/"

      - name: Deploy to OVH Swarm
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.OVH_HOST }}
          username: ${{ secrets.OVH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e

            docker run --rm \
            --network libero-net \
            -e NODE_ENV=production \
            -e PORT=3000 \
            -e POSTGRES_HOST=postgres \
            -e POSTGRES_PORT=5432 \
            -e POSTGRES_DB=libero \
            -e FRONTEND_URL=http://frontend \
            -e POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
            -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
            -e DATABASE_URL=postgresql://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@postgres:5432/libero \
            -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
            -e AWS_REGION=${{ secrets.AWS_REGION }} \
            -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            -e AWS_BUCKET_NAME=${{ secrets.AWS_BUCKET_NAME }} \
            ${{ env.IMAGE_BACKEND }} \
            sh -c "echo 'Waiting 15s for Postgres to initialize...' && sleep 15 && for i in {1..10}; do npx prisma migrate deploy && exit 0 || echo 'Prisma migrate failed, retrying in 5s...' && sleep 5; done; exit 1"